janitor:
  db:
    password: ${DATABASE_USER_PASSWORD}
    recreate-db-on-start: false
    update-db-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
  iam:
    # TODO(PF-81): Switch to use SAM instead of config file for user authZ.
    config-based-authz-enabled: ${CONFIG_BASED_AUTHZ_ENABLED}
    admin-user-list: ${ADMIN_USER_LIST:[]}
  primary:
    scheduler-enabled: true
  pubsub:
    track-resource:
      enabled: ${TRACK_RESOURCE_PUBSUB_ENABLED}
      project-id: ${TRACK_RESOURCE_PUBSUB_PROJECT_ID}
      subscription: ${TRACK_RESOURCE_PUBSUB_SUBSCRIPTION}
  server:
    port: 8080
  stackdriver:
    enabled: true
  stairway:
    db:
      password: ${STAIRWAY_DATABASE_USER_PASSWORD}
      uri: jdbc:postgresql://127.0.0.1:5432/${STAIRWAY_DATABASE_NAME}
      username: ${STAIRWAY_DATABASE_USER}
    force-clean-start: false
    max-parallel-flights: 40
    migrate-upgrade: true
    quiet-down-timeout: 20s
    terminate-timeout: 5s
    retention-check-interval: 1d
    completed-flight-retention: 7d
  azure:
    # TODO: read from vault
    managed-app-client-id: 51ef1ef2-b571-43b3-bcb3-ecaa3b49f0ed
    managed-app-client-secret:
    managed-app-tenant-id: fad90753-2022-4456-9b0a-c7e5b934e408

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application:
    name: janitor
  resources:
    cache.cachecontrol:
      max-age: 0
      must-revalidate: true
    static-locations: classpath:/api/
