DROP DATABASE IF EXISTS testdb;
DROP DATABASE IF EXISTS testdb-stairway;
DROP ROLE dbuser;
DROP ROLE dbuser-stairway;
CREATE DATABASE testdb;
CREATE DATABASE testdb-stairway;
CREATE ROLE dbuser WITH LOGIN ENCRYPTED PASSWORD 'dbpwd';
CREATE ROLE dbuser-stairway WITH LOGIN ENCRYPTED PASSWORD 'dbpwd-stairway';
