DROP DATABASE IF EXISTS testdb;
DROP DATABASE IF EXISTS testdb-stairway;
DROP ROLE dbuser;
CREATE DATABASE testdb;
CREATE DATABASE testdb-stairway;
CREATE ROLE dbuser WITH LOGIN ENCRYPTED PASSWORD 'dbpwd';
